
import { GoogleGenAI, Type } from "@google/genai";
import { Assignment, Submission, Feedback } from '../types';

if (!process.env.API_KEY) {
  console.warn("API_KEY environment variable not set. Using a placeholder.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

export const generateFeedback = async (assignment: Assignment, submission: Submission): Promise<Feedback> => {
  const model = 'gemini-2.5-pro';

  const rubricDetails = assignment.rubric.map(c => `- ${c.name} (Max points: ${c.maxPoints}, ID: ${c.id})`).join('\n');
  const submissionContent = `
    Textual Submission:
    ---
    ${submission.text}
    ---
    ${submission.audioUrl ? "\n[Student also provided an audio recording.]" : ""}
    ${submission.imageUrls && submission.imageUrls.length > 0 ? `\n[Student also provided ${submission.imageUrls.length} image(s).]` : ""}
  `;

  const prompt = `
    You are an expert in Chinese Culture and a helpful, encouraging high school teacher. 
    Your task is to grade a student's assignment based on a provided rubric and submission, providing detailed multimodal feedback.

    **Assignment Title:**
    ${assignment.title}

    **Assignment Instructions:**
    ${assignment.instructions}

    **Grading Rubric:**
    ${rubricDetails}

    **Student Submission:**
    ${submissionContent}

    **Your Task:**
    1.  Carefully evaluate the submission against EACH criterion in the rubric.
    2.  Provide a fair score and a specific, concise justification for each criterion.
    3.  Write a list of 2-3 specific strengths of the submission. Always start with positive feedback.
    4.  Write a list of 2-3 specific, actionable suggestions for improvement.
    5.  Write a brief, encouraging overall comment.
    6.  **Provide detailed, multimodal analysis:**
        *   **Text Analysis:** Comment on grammar, vocabulary, and content structure of the written Chinese text.
        *   **Image Analysis:** Assess the relevance and support the images provide for the written content. Analyze the image's connection to the assignment's cultural themes.
        *   **Audio Analysis:** Based on an assumed speech-to-text conversion, critique the content accuracy compared to the written text. Also, provide feedback on delivery, pacing, clarity, and pronunciation.
    7.  Return your entire evaluation as a JSON object that strictly follows the provided schema. Do not include any text, markdown, or code block delimiters outside of the JSON object.
    `;

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            strengths: { type: Type.ARRAY, items: { type: Type.STRING } },
            suggestions: { type: Type.ARRAY, items: { type: Type.STRING } },
            scores: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  criterionId: { type: Type.STRING },
                  score: { type: Type.NUMBER },
                  justification: { type: Type.STRING },
                },
                required: ["criterionId", "score", "justification"],
              },
            },
            overallComment: { type: Type.STRING },
            textAnalysis: {
                type: Type.OBJECT,
                properties: {
                    feedback: { type: Type.STRING, description: "Feedback on grammar, vocabulary, and content structure." }
                },
                required: ["feedback"],
            },
            imageAnalysis: {
                type: Type.OBJECT,
                properties: {
                    relevanceAndSupport: { type: Type.STRING, description: "Feedback on whether the images are well-aligned with and support the written content." },
                    contextualFeedback: { type: Type.STRING, description: "Analysis of the image's content and its connection to the assignment's cultural themes." }
                },
                required: ["relevanceAndSupport", "contextualFeedback"],
            },
            audioAnalysis: {
                type: Type.OBJECT,
                properties: {
                    contentAccuracy: { type: Type.STRING, description: "Feedback generated by comparing speech content to the written submission." },
                    deliveryAndPronunciation: { type: Type.STRING, description: "Feedback on pacing, clarity, and pronunciation." }
                },
                required: ["contentAccuracy", "deliveryAndPronunciation"],
            }
          },
          required: ["strengths", "suggestions", "scores", "overallComment", "textAnalysis", "imageAnalysis", "audioAnalysis"],
        },
      },
    });

    const feedbackJson = JSON.parse(response.text);
    
    // Validate that all rubric criteria were scored
    const scoredCriterionIds = new Set(feedbackJson.scores.map((s: any) => s.criterionId));
    const allCriterionIds = new Set(assignment.rubric.map(c => c.id));
    if (scoredCriterionIds.size !== allCriterionIds.size) {
        console.warn("AI did not score all rubric criteria.", {scoredCriterionIds, allCriterionIds});
    }

    return feedbackJson;
  } catch (error) {
    console.error("Error generating feedback from Gemini API:", error);
    throw new Error("Failed to get feedback from the AI. Please check the console for details.");
  }
};